Villa.WebUI/Controllers/FeatureController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Villa.Business.Abstract;
using Villa.Dto.Dtos.DealDtos;
using Villa.Dto.Dtos.FeatureDtos;
using Villa.Entity.Entities;

namespace Villa.WebUI.Controllers
{
    public class FeatureController : Controller
    {
        private readonly IFeatureService _featureService;
        private readonly IMapper _mapper;

        public FeatureController(IFeatureService featureService, IMapper mapper)
        {
            _featureService = featureService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _featureService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultFeatureDto>>(values);
            return View(valueList);
        }

        public async Task<IActionResult> DeleteFeature(ObjectId id)
        {
            await _featureService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateFeature()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateFeature(CreateFeatureDto createFeatureDto)
        {
            var newValue = _mapper.Map<Feature>(createFeatureDto);
            await _featureService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateFeature(ObjectId id)
        {
            var value = await _featureService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateFeatureDto>(value);
            return View(updateValue);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFeature(UpdateFeatureDto updateFeatureDto)
        {
            var updateValue = _mapper.Map<Feature>(updateFeatureDto);
            await _featureService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");
        }
    }
}

Villa.WebUI/Views/Feature/CreateFeature.cshtml
@model CreateFeatureDto
@{
    ViewData["Title"] = "Yeni Öne Çıkan Bilgisi Ekleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
 
    <label>Resim Url</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Alt Başlık</label>
    <input type="text" asp-for="SubTitle" class="form-control" />
    <br />
    <label>Metrekare</label>
    <input type="text" asp-for="Square" class="form-control" />
    <br />
    <label>Kontrat Türü</label>
    <input type="text" asp-for="Contract" class="form-control" />
    <br />
    <label>Ödeme Türü</label>
    <input type="text" asp-for="Payment" class="form-control" />
    <br />
    <label>Güvenlik Durumu</label>
    <input type="text" asp-for="Safety" class="form-control" />
    <br />
    
  
    <button class="btn btn-outline-dark">Kaydet</button>

</form>

Villa.WebUI/Views/Feature/Index.cshtml
@model List<ResultFeatureDto>
@{
    ViewData["Title"] = "Öne Çıkanlar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<table class="table table-hover table-bordered">
    @{
        int count = 0;
    }
    <tr>
        <th>#</th>
        <th>Resim Url</th>
        <th>Başlık</th>
        <th>Alt Başlık</th>
        <th>m2</th>
        <th>Kontrat Türü </th>
        <th>Ödeme Türü </th>
        <th>Güvenlik  </th>
        <th></th>

    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td><img src="@item.ImageUrl" style="height:50px;width:50px" /></td>
            <td>@item.Title</td>
            <td>@item.SubTitle</td>
            <td>@item.Square</td>
            <td>@item.Contract</td>
            <td>@item.Payment</td>
            <td>@item.Safety </td>
            

            <td>
                <button onclick="deleteFeature(this)" id="@item.Id" class="btn btn-outline-danger">Sil</button>
                <a asp-controller="Feature" asp-action="UpdateFeature" asp-route-id="@item.Id" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>
    }
</table>

<a asp-controller="Feature" asp-action="CreateFeature" class="btn btn-outline-dark">Yeni Öne Çıkan Bilgisi Ekle</a>



<script>
    function deleteFeature(button) {
        var id = button.getAttribute("id");
        Swal.fire({

            title: 'Silmek istediğinize emin misiniz?',
            text: 'Bu işlemi geri alamazsınız!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Evet, Sil!',
            cancelButtonText: 'İptal'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = "/Feature/DeleteFeature/" + id;
            }
        });
    };




</script>

Villa.WebUI/Views/Feature/UpdateFeature.cshtml
@model UpdateFeatureDto
@{
    ViewData["Title"] = "Öne Çıkan Bilgisi Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="Id" />
    <label>Resim Url</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Alt Başlık</label>
    <input type="text" asp-for="SubTitle" class="form-control" />
    <br />
    <label>Metrekare</label>
    <input type="text" asp-for="Square" class="form-control" />
    <br />
    <label>Kontrat Türü</label>
    <input type="text" asp-for="Contract" class="form-control" />
    <br />
    <label>Ödeme Türü</label>
    <input type="text" asp-for="Payment" class="form-control" />
    <br />
    <label>Güvenlik Durumu</label>
    <input type="text" asp-for="Safety" class="form-control" />
    <br />


    <button class="btn btn-outline-dark">Güncelle</button>

</form>